# Generated by Django 4.1 on 2023-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
