# Generated by Django 4.1 on 2023-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListapp', '0002_alter_tododata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
